dist: focal
language: node_js
node_js:
  - 13

services:
  - docker

before_install:
  - sudo apt install --only-upgrade docker-ce -y

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker compose build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker compose push