dist: focal
language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version
  - docker compose build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker compose push